Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.

In [16]:
def find_triangular(limit):
    triangular=[int(n*(n+1)/2) for n in range (1, limit)]
    return triangular

def find_hexagonal(limit):
    hexagonal=[int(n*(2*n-1)) for n in range (1, limit)]
    return hexagonal

def is_pentagonal(num):
    n=(1+(24*num+1)**0.5)/6
    #print (n)
    if n%1==0:
        return True
    else:
        return False

[1, 3, 6, 10, 15, 21, 28, 36, 45, 55, 66, 78, 91, 105, 120, 136, 153, 171, 190, 210, 231, 253, 276, 300, 325, 351, 378, 406, 435, 465, 496, 528, 561, 595, 630, 666, 703, 741, 780, 820, 861, 903, 946, 990, 1035, 1081, 1128, 1176, 1225, 1275, 1326, 1378, 1431, 1485, 1540, 1596, 1653, 1711, 1770, 1830, 1891, 1953, 2016, 2080, 2145, 2211, 2278, 2346, 2415, 2485, 2556, 2628, 2701, 2775, 2850, 2926, 3003, 3081, 3160, 3240, 3321, 3403, 3486, 3570, 3655, 3741, 3828, 3916, 4005, 4095, 4186, 4278, 4371, 4465, 4560, 4656, 4753, 4851, 4950]
[1, 6, 15, 28, 45, 66, 91, 120, 153, 190, 231, 276, 325, 378, 435, 496, 561, 630, 703, 780, 861, 946, 1035, 1128, 1225, 1326, 1431, 1540, 1653, 1770, 1891, 2016, 2145, 2278, 2415, 2556, 2701, 2850, 3003, 3160, 3321, 3486, 3655, 3828, 4005, 4186, 4371, 4560, 4753, 4950, 5151, 5356, 5565, 5778, 5995, 6216, 6441, 6670, 6903, 7140, 7381, 7626, 7875, 8128, 8385, 8646, 8911, 9180, 9453, 9730, 10011, 10296, 10585, 10878, 11175, 11476, 11781, 12090, 12403, 12720, 13041, 13366, 13695, 14028, 14365, 14706, 15051, 15400, 15753, 16110, 16471, 16836, 17205, 17578, 17955, 18336, 18721, 19110, 19503]

In [25]:
def find_triplet(start):
    
    while True:
        number=start*(start+1)/2
        if is_pentagonal(number):
            return int(number), start
        start+=2

In [26]:
number, idx= find_triplet(287)

In [27]:
print (number, idx)

1533776805 55385